### ISSUE TITLE
Slightly different restraints for dummy hydrogens at the physical endpoints can --- in principal -- effect the results

### ISSUE THREAD

**Issue by wiederm** [choderalab/neutromeratio#16]
@jchodera , @maxentile : We add restraints to confine all hydrogens, including the dummy atom during the simulation.
After reviewing the code I realize that the dummy atom restraints on the physical endpoints can differ, depending on the heavy atom they are connected to. What I mean is that dummy atom 1 can have a slightly different harmonic well restraint than dummy atom 2, because the equilibrium bond length between the physical hydrogen and the heavy atom differs. 

This can have an effect on the final free energy, since -- while we have on both endpoints a non-interacting sphere that is bumping into a restraint -- the area the dummy atom has access to is not the same on the physical endpoints. As it is now the bottom well restraint is defined with equilibrium_length +- 0.4 Angstrom, and the equilibrium_length is different for Nitrogen, Carbon and Oxygen.

I looked into this and generated plots for three systems in which the hydrogen is attached to a different heavy atom at the endpoints. The plots show the difference between the restraint energies at lambda=0,1.
![image](https://user-images.githubusercontent.com/31651017/97109279-a610e380-16d2-11eb-8a08-9d18fe838e91.png)
![image](https://user-images.githubusercontent.com/31651017/97109291-b032e200-16d2-11eb-9ec8-70ae0ea70845.png)
![image](https://user-images.githubusercontent.com/31651017/97109294-b7f28680-16d2-11eb-8923-ccbefd28ad45.png)

While this is technically an error and adds artificial contributions to the endstate, it seems as if it is very unlikely that it will change the results. I will still rerun the simulations with a fixed dummy atom restraint.

**Comment by maxentile** [comment]
Thank you for identifying and looking into this issue! And it's good that you instrumented the code to save the applied bias early on, so that it's possible to double-check things like this after the fact.

I imagine this could in principle affect the results, but based on these plots it seems unlikely to have had a large effect.

>I will still rerun the simulations with a fixed dummy atom restraint.

An approach that would ensure the dummy atom restraint doesn't contribute, as you mention, would be to set both flat-bottom restraints to be [constant +/- 0.4A], where the same constant is shared by both hydrogens. (Perhaps a good choice would be constant = 0.5 * (eq_A + eq_B) )

Clarification question: is the equilibrium length of either dummy atom restraint currently changing as a function of lambda? If restraint on hydrogen A is the same at lambda=0 and 1, and separately the restraint on hydrogen B is the same at lambda=0 and 1, this might still be fine, but I'll need to give this a more careful think...

**Comment by wiederm** [comment]
> An approach that would ensure the dummy atom restraint doesn't contribute, as you mention, would be to set both flat-bottom restraints to be [constant +/- 0.4A], where the same constant is shared by both hydrogens. (Perhaps a good choice would be constant = 0.5 * (eq_A + eq_B) )

Agreed. That would solve this issues IMO.

> Clarification question: is the equilibrium length of either dummy atom restraint currently changing as a function of lambda? If restraint on hydrogen A is the same at lambda=0 and 1, and separately the restraint on hydrogen B is the same at lambda=0 and 1, this might still be fine, but I'll need to give this a more careful think...
Restraints are **NOT** changing as a function of lambda. They are always on or off --- but these are so far away from where the atoms should be that they only ever activate when either a bond is broken or the atom is a dummy atom.

**Comment by jchodera** [comment]
`0.5 * (eq_A + eq_B)` sounds like a good choice to me!
